In [3]:
df1

      soc hours  estpay  change
0    1115    36    1970     2.6
1    1116    50     840    29.1
2    1121    37    1060     1.9
3    1122    41    1000    -2.9
4    1123    39     990   -14.7
..    ...   ...     ...     ...
362  9272    39     340    -0.9
363  9273    38     330     4.8
364  9274    36     310     3.9
365  9275    32     360    -1.1
366  9279    35     320     3.5

[367 rows x 4 columns]

In [1]:
from LMI_API1 import *

[1115, 36, 1970, 2.6]
[1116, 50, 840, 29.1]
[1121, 37, 1060, 1.9]
[1122, 41, 1000, -2.9]
[1123, 39, 990, -14.7]
[1131, 38, 1460, 0.3]
[1132, 37, 1540, -4.8]
[1133, 35, 980, 1.5]
[1134, 41, 1330, 5.0]
[1135, 37, 1020, 3.8]
[1136, 38, 1470, 10.0]
[1139, 38, 1210, -1.6]
[1150, 33, 1130, -2.0]
[1161, 38, 810, 4.2]
[1162, 38, 600, 2.0]
[1172, 40, 1070, -5.5]
[1173, 40, 850, -9.6]
[1181, 39, 1040, 9.4]
[1184, 39, 820, 2.2]
[1190, 38, 650, 3.1]
[1211, 45, 660, -5.9]
[1213, 56, 690, 7.3]
[1221, 63, 930, 4.0]
[1223, 55, 680, 2.0]
[1224, 56, 680, -5.4]
[1225, 52, 890, 14.0]
[1226, 52, 900, 10.6]
[1241, 57, 1030, -4.3]
[1242, 48, 820, 2.1]
[1251, 49, 960, 2.5]
[1252, 68, 1310, 19.3]
[1253, 49, 510, -12.6]
[1254, 74, 1250, -14.3]
[1255, 53, 100, 2.0]
[1259, 52, 1010, 0.9]
[2111, 40, 750, 0.4]
[2112, 37, 780, 4.0]
[2113, 42, 960, -0.2]
[2114, 45, 700, 5.5]
[2119, 41, 840, 3.7]
[2121, 38, 790, 0.5]
[2122, 38, 860, 2.5]
[2123, 39, 930, 5.8]
[2124, 41, 890, 5.7]
[2126, 37, 820, 0.9]
[2127, 38, 790, -0.6]
[2129, 38, 790, 0.5]
[2133, 37, 940, 0.1]
[2134, 37, 1040, -0.2]
[2135, 37, 960, 4.6]
[2136, 36, 860, 5.0]
[2137, 35, 580, 3.8]
[2139, 36, 790, 6.1]
[2141, 39, 650, -5.1]
[2142, 37, 710, 2.8]
[2150, 37, 960, 5.5]
[2211, 34, 1140, -0.6]
[2212, 32, 690, 1.2]
[2213, 30, 610, -4.1]
[2214, 26, 710, 7.5]
[2215, 23, 700, 12.9]
[2216, 36, 660, -4.8]
[2217, 37, 720, 4.2]
[2218, 22, 440, 4.7]
[2219, 31, 630, 4.0]
[2221, 34, 610, 3.8]
[2222, 34, 620, -0.4]
[2223, 35, 610, 11.7]
[2229, 25, 420, 3.4]
[2231, 36, 660, 4.0]
[2232, 35, 710, 1.4]
[2311, 35, 1020, 0.1]
[2312, 31, 650, -1.3]
[2314, 31, 730, 0.3]
[2315, 28, 610, 2.5]
[2316, 27, 530, 2.2]
[2317, 30, 900, 0.9]
[2318, 30, 600, 5.4]
[2319, 20, 300, 6.6]
[2412, 28, 660, 2.6]
[2413, 30, 870, 3.7]
[2419, 33, 1380, 0.7]
[2421, 33, 720, 8.2]
[2423, 33, 780, -0.9]
[2424, 35, 990, 4.4]
[2425, 36, 970, -11.1]
[2426, 34, 660, 4.2]
[2429, 34, 760, 2.0]
[2431, 31, 730, 1.3]
[2432, 36, 750, 7.0]
[2433, 36, 810, 5.6]
[2434, 33, 670, 0.9]
[2435, 39, 750, 10.4]
[2436, 38, 770, -0.3]
[2442, 36, 690, 2.5]
[2443, 34, 580, 20.9]
[2444, 30, 420, 6.4]
[2449, 35, 600, 1.7]
[2451, 33, 540, -0.8]
[2452, 29, 460, -0.5]
[2461, 36, 700, -0.4]
[2462, 34, 870, 3.3]
[2463, 39, 680, -0.2]
[2471, 30, 610, 5.0]
[2472, 33, 610, 1.9]
[2473, 31, 800, 6.8]
[3111, 34, 440, 5.6]
[3112, 37, 640, -1.9]
[3113, 35, 600, -0.4]
[3114, 36, 590, -5.2]
[3115, 35, 530, 7.3]
[3116, 33, 520, -1.5]
[3119, 35, 500, 1.7]
[3121, 35, 490, 0.2]
[3122, 34, 540, 5.8]
[3131, 33, 570, 5.4]
[3132, 33, 540, 6.8]
[3213, 38, 740, 1.1]
[3216, 32, 420, -7.6]
[3217, 33, 410, 6.2]
[3218, 37, 560, 1.8]
[3219, 35, 430, -4.2]
[3231, 32, 450, -5.1]
[3233, 33, 430, 1.0]
[3234, 33, 500, 2.8]
[3235, 33, 560, 3.0]
[3239, 33, 440, 4.9]
[3312, 40, 790, 1.1]
[3313, 42, 690, 2.2]
[3314, 39, 570, 0.1]
[3315, 38, 490, 4.4]
[3319, 34, 680, 5.1]
[3411, 35, 480, -1.3]
[3412, 33, 650, 4.7]
[3413, 43, 0, -999.0]
[3414, 'data not new enough', 0, -999.0]
[3415, 22, 760, 7.9]
[3416, 38, 940, 4.5]
[3417, 36, 570, 5.3]
[3421, 38, 600, 3.4]
[3422, 33, 520, 0.5]
[3441, 39, 170, -999.0]
[3442, 36, 540, 4.9]
[3443, 26, 350, 7.8]
[3511, 47, 1840, 11.6]
[3512, 40, 1710, -8.4]
[3513, 40, 900, 6.3]
[3520, 35, 670, 5.2]
[3531, 37, 710, 6.0]
[3532, 38, 1670, -2.5]
[3533, 36, 850, 11.0]
[3534, 35, 810, 7.8]
[3535, 33, 940, 6.7]
[3536, 39, 560, -2.9]
[3537, 37, 880, -1.4]
[3538, 37, 860, 4.9]
[3539, 36, 620, -1.4]
[3541, 37, 620, -0.9]
[3542, 37, 660, 6.3]
[3543, 36, 570, 2.0]
[3544, 36, 490, 4.8]
[3545, 38, 970, 3.6]
[3546, 36, 500, -2.1]
[3550, 36, 440, -9.6]
[3561, 40, 690, 18.4]
[3562, 38, 590, 0.7]
[3563, 38, 610, -1.3]
[3564, 38, 590, -0.6]
[3565, 37, 710, 8.1]
[3567, 37, 730, 2.8]
[4112, 39, 550, 10.2]
[4113, 38, 530, 3.4]
[4114, 35, 560, -13.2]
[4121, 36, 460, 1.6]
[4122, 35, 510, 2.3]
[4123, 36, 500, 1.5]
[4124, 36, 550, 4.2]
[4129, 36, 450, 5.7]
[4131, 38, 470, 2.0]
[4132, 37, 470, 5.2]
[4133, 37, 450, 2.4]
[4134, 39, 490, 0.4]
[4135, 34, 440, 0.5]
[4138, 37, 420, -2.3]
[4151, 36, 430, 6.9]
[4159, 37, 490, 6.7]
[4161, 37, 650, 3.6]
[4162, 38, 520, 7.5]
[4211, 47, 570, 4.3]
[4212, 38, 480, 2.7]
[4213, 47, 520, 4.0]
[4214, 29, 580, -1.5]
[4215, 41, 610, -3.3]
[4216, 42, 430, 5.2]
[4217, 40, 440, 9.0]
[5111, 116, 1270, -3.1]
[5112, 75, 680, -1.0]
[5113, 79, 840, 4.6]
[5114, 60, 610, 4.3]
[5119, 70, 810, 3.1]
[5211, 27, 0, -13.4]
[5212, 46, 520, -15.8]
[5213, 47, 590, -4.9]
[5214, 52, 710, -4.4]
[5215, 47, 620, 5.0]
[5216, 57, 980, 15.1]
[5221, 46, 610, 3.8]
[5222, 47, 670, 9.5]
[5223, 46, 740, 4.0]
[5224, 46, 580, -4.3]
[5225, 55, 800, -4.0]
[5231, 49, 630, 4.2]
[5232, 53, 650, -0.4]
[5234, 47, 580, 10.3]
[5235, 51, 940, 0.3]
[5236, 56, 740, 4.8]
[5237, 46, 840, 0.2]
[5241, 45, 710, 4.4]
[5242, 44, 720, 0.9]
[5244, 48, 680, -9.1]
[5245, 42, 750, -0.9]
[5249, 45, 730, 3.4]
[5250, 46, 800, 3.5]
[5311, 53, 700, 10.1]
[5312, 46, 620, 8.3]
[5313, 43, 550, -2.0]
[5314, 46, 680, 2.4]
[5315, 45, 590, 4.8]
[5316, 48, 500, 2.9]
[5319, 44, 600, 3.7]
[5321, 44, 590, 2.0]
[5322, 45, 560, -8.2]
[5323, 44, 530, 6.5]
[5330, 46, 810, 7.6]
[5411, 42, 450, 7.6]
[5412, 34, 410, 5.7]
[5413, 45, 450, -9.1]
[5414, 27, 500, 9.9]
[5419, 39, 450, -8.0]
[5421, 39, 590, 3.8]
[5422, 39, 500, 4.1]
[5423, 41, 420, 10.4]
[5431, 42, 450, 6.5]
[5432, 37, 350, 7.0]
[5433, 39, 350, 1.3]
[5434, 39, 430, 1.6]
[5435, 37, 370, 3.9]
[5436, 37, 420, 0.9]
[5441, 46, 440, 29.4]
[5442, 40, 420, 8.5]
[5443, 32, 330, -17.1]
[5449, 37, 490, 8.7]
[6121, 31, 290, 2.3]
[6122, 27, 300, 8.5]
[6123, 14, 200, 9.4]
[6125, 29, 300, 3.6]
[6126, 29, 300, 1.6]
[6131, 33, 350, -0.9]
[6132, 31, 320, 19.1]
[6139, 26, 260, 5.4]
[6141, 31, 350, 2.8]
[6142, 36, 450, 6.4]
[6143, 32, 320, 5.2]
[6144, 30, 360, 5.8]
[6145, 31, 310, 4.5]
[6146, 35, 360, 2.8]
[6147, 14, 260, 17.7]
[6148, 32, 400, 8.2]
[6211, 38, 390, -0.3]
[6212, 38, 440, 4.7]
[6214, 36, 410, -27.1]
[6215, 38, 700, -1.7]
[6219, 30, 480, 9.1]
[6221, 33, 320, -2.0]
[6222, 36, 360, -1.1]
[6231, 31, 310, 2.5]
[6232, 40, 430, 3.7]
[6240, 32, 330, 0.9]
[7111, 32, 330, 2.3]
[7112, 29, 270, -1.2]
[7113, 38, 430, 2.3]
[7114, 33, 310, 1.7]
[7115, 41, 490, 12.8]
[7121, 38, 340, 9.8]
[7122, 35, 360, 5.2]
[7123, 37, 380, 11.7]
[7124, 33, 0, -999.0]
[7125, 32, 390, 8.2]
[7129, 34, 410, 3.9]
[7130, 35, 410, 2.5]
[7211, 33, 350, 5.2]
[7213, 30, 330, 6.3]
[7214, 34, 490, -0.6]
[7215, 17, 370, 9.7]
[7219, 33, 380, 6.1]
[7220, 33, 510, 7.0]
[8111, 44, 460, 5.8]
[8112, 49, 550, 2.9]
[8113, 44, 490, 2.3]
[8114, 45, 660, 1.1]
[8115, 52, 560, 5.8]
[8116, 47, 520, -3.5]
[8117, 48, 590, 7.0]
[8118, 51, 530, 1.6]
[8119, 52, 570, 4.9]
[8121, 46, 500, 7.3]
[8122, 'data not new enough', 660, -999.0]
[8123, 60, 760, 13.1]
[8124, 48, 810, -2.7]
[8125, 45, 520, 4.9]
[8126, 45, 590, 11.4]
[8127, 43, 490, 6.6]
[8129, 47, 550, -8.5]
[8131, 48, 470, 4.6]
[8132, 44, 600, 3.5]
[8133, 43, 590, 4.8]
[8134, 44, 470, -2.3]
[8135, 49, 480, 5.5]
[8137, 35, 340, 4.2]
[8139, 44, 490, -0.6]
[8141, 49, 780, 8.5]
[8142, 52, 690, 6.7]
[8143, 47, 690, -9.0]
[8149, 49, 590, 13.4]
[8211, 48, 600, 3.6]
[8212, 45, 490, 3.4]
[8213, 42, 510, 2.4]
[8214, 41, 490, 4.8]
[8215, 14, 180, -22.7]
[8221, 57, 850, 7.2]
[8222, 42, 470, 2.8]
[8223, 51, 490, 21.7]
[8229, 47, 660, 4.5]
[8231, 39, 1110, 6.6]
[8232, 46, 630, -7.9]
[8233, 44, 550, -2.5]
[8234, 44, 800, -25.2]
[8239, 42, 570, 14.0]
[9111, 58, 580, 3.6]
[9112, 57, 630, 4.2]
[9119, 49, 450, 6.8]
[9120, 64, 720, -0.4]
[9132, 45, 420, 21.3]
[9134, 44, 450, 3.6]
[9139, 47, 520, 7.6]
[9211, 39, 510, 13.4]
[9219, 43, 420, 8.0]
[9231, 31, 350, -13.1]
[9232, 36, 370, -0.2]
[9233, 43, 400, 5.0]
[9234, 39, 360, 1.9]
[9235, 38, 390, 1.3]
[9236, 42, 370, 5.7]
[9239, 38, 470, 2.8]
[9241, 43, 460, 2.8]
[9242, 38, 390, 2.3]
[9244, 16, 500, 3.3]
[9249, 34, 440, 5.0]
[9251, 34, 330, -2.2]
[9259, 31, 340, -10.9]
[9260, 39, 420, 3.2]
[9271, 40, 430, 2.3]
[9272, 39, 340, -0.9]
[9273, 38, 330, 4.8]
[9274, 36, 310, 3.9]
[9275, 32, 360, -1.1]
[9279, 35, 320, 3.5]
done

In [3]:
df1

      soc hours  estpay  change
0    1115    36    1970     2.6
1    1116    50     840    29.1
2    1121    37    1060     1.9
3    1122    41    1000    -2.9
4    1123    39     990   -14.7
..    ...   ...     ...     ...
362  9272    39     340    -0.9
363  9273    38     330     4.8
364  9274    36     310     3.9
365  9275    32     360    -1.1
366  9279    35     320     3.5

[367 rows x 4 columns]